name: deploy

on:
  push:
    # Run for all branches except the main branch
    branches-ignore:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      - name: Update REPO file
        run: |
          wget -P /tmp -q https://crux.nu/files/httpup-0.5.0.tar.xz
          tar -C /tmp -xf /tmp/httpup-0.5.0.tar.xz httpup-0.5.0/httpup-repgen
          /tmp/httpup-0.5.0/httpup-repgen
          git add REPO

      - name: Push to remote
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          bash -c "git commit -a -m '[auto] Update REPO file' && git push || exit 0" 
